### ISSUE TITLE
tags.conf references an eventtype that does not exist in eventtypes.conf

### ISSUE THREAD

**Issue by jomartin93** [PaloAltoNetworks/Splunk-Apps#198] opened 2021-07-19 16:19 UTC
Discovered this issue when attempting to pull events from the Endpoint.Processes dataset. Received the error:

Eventtype 'pan_endpoint_process' does not exist or is disabled.

Located the endpoint and process tags, saw they were pointing to eventtype=pan_endpoint_process. This eventtype did not exist.

Closer inspection into the 7.0.1 TA revealed that tags.conf contains the following stanza:
[eventtype=pan_endpoint_process]
endpoint = enabled
process  = enabled

But eventtype.conf does not have a [pan_endpoint_process] stanza. Additionally, tags.conf references the following eventtypes that don't exist in eventtype.conf:

pan_endpoint_change
pan_endpoint_alert
pan_endpoint_authentication
pan_endpoint_process

**Comment by paulmnguyen** [comment] 2021-07-19 17:13
Thanks for reporting the issue. We have already implemented a fix that will go out in the next release. Please checkout Issues #193 

Duplicate of #193

**Closed by paulmnguyen** 2021-07-19 17:13 UTC
