### ISSUE TITLE
"A custom JavaScript error caused an issue loading your dashboard....." Palo Alto Networks Splunk App

### ISSUE THREAD

**Issue by DarthW1** [PaloAltoNetworks/Splunk-Apps#208] opened 2021-08-23 19:14 UTC
## Describe the bug

When going to the Threats and Activities dashboards in the Palo Alto Networks App on SplunkCloud I get the error "A custom JavaScript error caused an issue loading your dashboard, likely due to the dashboard version update.  See the developer console for more details".  I can close the error, and best I can tell the dashboard works normally.  If I look at the developer console there is a dashboard.js that seems to be faulting as best I can tell. 

I updated the Palo Alto Networks App in Splunk to the latest version and still no fix. On version 7.0 now.  The issue occurs with at least Chrome and Firefox, and occurs to other users on other systems, so it's not isolated to a single system.  The problem seems to be the dashboard.

Any solutions?  All I have to do to replicate it is click any dashboard under the Threats or the Activities menus.

![image](https://user-images.githubusercontent.com/89087220/130504434-0882cf96-af92-4c51-b6ab-25a80aea54a6.png)

Again this error occurs on Windows, using the Palo Altos Network App version 7.0 using the latest Chrome or Firefox.

**Comment by DarthW1** [comment] 2021-09-20 13:01
This error is still an issue.  My understanding was that Palo Alto was preparing an update to correct the problem.  But it is still showing the error.

**Comment by paulmnguyen** [comment] 2021-09-21 22:10
Closing as duplicate of #197

**Closed by paulmnguyen** 2021-09-21 22:10 UTC
Labels: bug

**Comment by Cliffcy** [comment] 2022-03-28 03:50
v7.04 also have this problem. Any suggestion from Splunk?

**Comment by Cliffcy** [comment] 2022-03-28 04:08
![image](https://user-images.githubusercontent.com/102500071/160325024-ce45ef91-8ca2-4db2-8b81-393e3a6ac26a.png)

**Comment by sreekanthdundigala** [comment] 2023-03-02 11:10
remove all unnecessary javascript files from <form> / <dashboard> and see if the existing and fixing those will not give the custom javascript error.
